---
# ansible-playbook -i yourinventory add-service-account-sudo.yml --extra-vars="target=<<target-name>>"
# To run without passwordless ssh/sudo - since you're probably running this because you don't already have a service account - We disable pipelining because ttyless is required, and might not be enabled yet:
# env ANSIBLE_PIPELINING=0 ansible-playbook -i yourinventory add-service-account-sudo.yml --extra-vars="target=<<target-name>>" -u remote_user --ask-become-pass --become --ask-pass

- hosts: "{{ target }}"
  become: yes

  tasks:  
  - name: Add Openshift user
    user:
      name: openshift
      group: wheel

  - name: Set authorized key taken from file
    authorized_key:
      user: openshift
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"        
        
  - name: Allow openshift to sudo        
    lineinfile:
      path: /etc/sudoers
      state: present
      insertafter: '^Defaults    requiretty'
      line: 'Defaults:openshift !requiretty'
      validate: '/usr/sbin/visudo -cf %s'
