---


- name: Register Servers into RHSM
  hosts: all

  become: yes
  vars:

    rhsm_ose_repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ose-3.11-rpms
      - rhel-7-server-ansible-2.6-rpms

  tasks:

  - name: Register master/infra into rhsm
    shell: subscription-manager attach --pool 66666666666666666666666666666666
    when: ( 'masters' in group_names ) or ( 'infras' in group_names )

  - name: Register compute into rhsm 
    shell: subscription-manager attach --pool 66666666666666666666666666666666
    when: ( 'appnodes' in group_names )

  - name: Register compute into rhsm 
    shell: subscription-manager repos --disable="*"

  - name: Enable specified repositories not already enabled for Open Shift systems
    shell: "subscription-manager repos --enable={{ item }}"
    with_items:
      - "{{ rhsm_ose_repos | difference(enabled_repos.stdout_lines) }}"
